// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWH8QOt5YuBGQ6P7zMLrgYrjuRbDYJJRQ',
    appId: '1:293582260187:web:5b6e145241ad1efd9b49fe',
    messagingSenderId: '293582260187',
    projectId: 'total-x-608fd',
    authDomain: 'total-x-608fd.firebaseapp.com',
    storageBucket: 'total-x-608fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCtN0RmzKcuLRmZlD98DBcDdTNXFy8g9A',
    appId: '1:293582260187:android:a681edc23c37f1af9b49fe',
    messagingSenderId: '293582260187',
    projectId: 'total-x-608fd',
    storageBucket: 'total-x-608fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVptvt629ChFipcuAVgksxt0A0ZfJWdzI',
    appId: '1:293582260187:ios:229c4f9b52ec5bd79b49fe',
    messagingSenderId: '293582260187',
    projectId: 'total-x-608fd',
    storageBucket: 'total-x-608fd.appspot.com',
    iosBundleId: 'com.example.mechinetestTotalx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVptvt629ChFipcuAVgksxt0A0ZfJWdzI',
    appId: '1:293582260187:ios:229c4f9b52ec5bd79b49fe',
    messagingSenderId: '293582260187',
    projectId: 'total-x-608fd',
    storageBucket: 'total-x-608fd.appspot.com',
    iosBundleId: 'com.example.mechinetestTotalx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWH8QOt5YuBGQ6P7zMLrgYrjuRbDYJJRQ',
    appId: '1:293582260187:web:e3550fae625266399b49fe',
    messagingSenderId: '293582260187',
    projectId: 'total-x-608fd',
    authDomain: 'total-x-608fd.firebaseapp.com',
    storageBucket: 'total-x-608fd.appspot.com',
  );
}
